### ISSUE TITLE
Slash Command Privileges

### ISSUE THREAD

**Issue by TheLeCrafter** [ruffrick/jda-commands#1]
Add a ``@Privilege`` annotation to support Slash Command privileges.

https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/interactions/commands/Command.html#updatePrivileges(net.dv8tion.jda.api.entities.Guild,net.dv8tion.jda.api.interactions.commands.privileges.CommandPrivilege...)

**Comment by ruffrick** [comment]
I added some functionality supporting that, use `@Privileges` on your command class and add as many as you like. I haven't extensively tested it yet, initial tests show it working fine. I'm not really happy with the way it updates the privileges yet (you have to make sure the guilds you want to add privileges for are cached before calling `updateCommands()`, e. g. by `awaitReady()`-ing your JDA instance(s)). Any feedback is appreciated ^^

**Comment by TheLeCrafter** [comment]
Great to see your support on this project. I will look into it and give you some feedback.

**Comment by TheLeCrafter** [comment]
The annotation currently breaks on Subcommand classes. Seems like the command couldn't be found. (RestAction queue returned failure: [ErrorResponseException] 10063: Unknown application command)

**Comment by ruffrick** [comment]
Not quite sure what happened there, I can't seem to reproduce it...
```kt
@Command(enabled = false)
@Privileges(<guildId>, Privilege(CommandPrivilege.Type.USER, true, <userId>))
class TestCommand : SlashCommand() {
    @Subcommand
    fun sub1(event: SlashCommandInteractionEvent) {
        event.reply("Subcommand 1").setEphemeral(true).queue()
    }

    @Subcommand
    fun sub2(event: SlashCommandInteractionEvent) {
        event.reply("Subcommand 1").setEphemeral(true).queue()
    }
}

```
Works fine for me, or am I misunderstanding your problem?

**Comment by TheLeCrafter** [comment]
```kotlin
@Command(name="test", description="Just a command to test stuff", enabled = false)
@Privileges(guildId = <guildId>, Privilege(CommandPrivilege.Type.USER, true, <myId>))
class MyTestCommand : SlashCommand() {

    @Subcommand(name="first", "Test subcommand one")
    fun first(event: SlashCommandInteractionEvent, @Option("option", "Test option") option: String) {
        event.deferReply(false).queue()
            event.hook.sendMessage("Test subcommand one").queue()
    }

    @Subcommand(name="second", "Test subcommand two")
    fun second(event: SlashCommandInteractionEvent, @Option("anotheroption", "Very cool option") option: String) {
        event.deferReply(false).queue()
            event.hook.sendMessage("Test subcommand two").queue()
    }
}

**Comment by ruffrick** [comment]
Just ran that exact code, both as a guild command and as a global command. No issues here. I'm able to use it, other users are not. How are you registering the commands (where\how do you create the CommandRegistry etc.)? I have checked every corner that I could imagine, but still can't reproduce it...
Edit: Also make sure you're using the latest versions of JDA (alpha.6) and jda-kotlinx ([90bdb86](https://github.com/ruffrick/jda-kotlinx/commit/90bdb86c748df3c182f359155ff78742f009e3cb)) as well. Should not make a difference, just for consistencies sake.
